### ISSUE TITLE
format of the json input file? support for hierarchical clustering?

### ISSUE THREAD

**Issue by paul-shannon** [MaayanLab/clustergrammer-web#1]
Is there documentation for the json input files?  I see row_nodes, col_nodes, links, and reverse engineering the formal structure might not be so hard.  But a formal statement of the expected file structure would be very helpful.  

For what it's worth, I will be generating matrices in R, sending them as JSON over websockets to the browser.    

Is there any support - now, or planned - for hierarchical clustering?  It -seems- (to my eye, on first look) that the clustering of rows and columns is more flat than tree-like.

Thanks for this very fine javascript widget.
- Paul

**Comment by cornhundred** [comment]
Hi Paul,

Thanks for your interest. I'm still updating the documentation for the JSON
format. Here is a link to the current documentation
https://github.com/MaayanLab/clustergrammer#clustergrammer-json-format

And here is an example json -
https://github.com/MaayanLab/clustergrammer/blob/master/json/mult_view.json

The format does support hierarchical clustering - each clustergram has 10
hierarchical group levels. You can encode this in the group value. Here's
an interactive demo that shows how to interact with the dendrogram here
http://amp.pharm.mssm.edu/clustergrammer/

You can also use the clustergrammer.py module to produce the json
https://github.com/MaayanLab/clustergrammer#clustergrammer-python-module

I'll let you know when I've updated the documentation. Please let me know
if you have any questions.

Best,
Nick

**Comment by paul-shannon** [comment]
Hi Nick,

Thanks for these answers and suggestions.

Wishing to get a quick start, and deferring R for a while, I just spent some time trying to get clustergrammer.py working on rc_two_cats.txt.  Discovering that your code is python 2.7, not 3.5, I hacked my way through a partial revision of your code, hoping to squeak out that quick start.  I didn’t quite make it.

Maybe a >= 3.5.1 version of your package is in the works?

Now I will turn to your docs on the json format, so how that goes.

I am eager to use your heatmap.  Thanks again.

 - Paul

**Comment by paul-shannon** [comment]
I installed python 2.7.  Everything works great.   Very nice software!

If you are so inclined, support for python > 3.5 would be useful to us here at the ISB.

 - Paul

**Comment by cornhundred** [comment]
Paul,

Great, I'm glad that worked out. I agree that python 3.5 support is a good
idea and I'll let you know when that is available :)

Thanks for the feedback.

Best,
Nick

**Comment by paul-shannon** [comment]
Hi Nick,

I’ve been able to use your heat map in my own webapp.   I now wish to strip out some of the controls you offer, these in particular (starting with the x button and “Share the visualization..”).

Where can I read in order to learn to do that?

Thanks!

 - Paul

**Comment by cornhundred** [comment]
Hi Paul, 

That's great. I still need to document more of the controls, but you can get rid of the share, help and camera icons using the optional argument to Clustergrammer.js 
`
      // define arguments object
      var args = {
        root: '#container-id-1',
        'network_data': network_data,
        'about':'Zoom, scroll, and click buttons to interact with the clustergram.',
        'sidebar_icons':false
      };
`

The last 'sidebar_icons' part is what you want. Also you can also remove any component in a hacky way using d3 like this 

`d3.selectAll('.expand_button').remove();`

I hope that helps. I'll will let you know when I've updated the documentation. 

Best,
Nick

**Comment by cornhundred** [comment]
Paul, 

Since you are using the JavaScript and Python code on its own, these questions are more appropriate for the clustergrammer repo here:

https://github.com/MaayanLab/clustergrammer 

Currently, we're on the clustergrammer-web repo that hosts the code for 

http://amp.pharm.mssm.edu/clustergrammer/

Best, 
Nick
