### ISSUE TITLE
Downloading matrix with cluster information

### ISSUE THREAD

**Issue by vwongjun** [MaayanLab/clustergrammer-web#13]
I was wondering if it is possible to download a matrix with cluster information in it? 
It would be very helpful to have the clustering information in the matrix that is downloaded otherwise I have to go through all the different clusters manually which is really time-consuming given the amount of data I have in input.

Thanks.

**Comment by u8sand** [comment]
Hi @vwongjun -- the best way to do this is to compute it locally using the python clustergrammer library directly.  But if you really need to get this information out of the site, you can do the following with python:

```python
import re
import json
import requests
import pandas as pd

url = 'https://maayanlab.cloud/clustergrammer/viz/58a492b4a63cb826f0be6476/sim_col:rc_two_cats.txt'
network_data = json.loads(re.search(r'network_data = (.+);', requests.get(url).text).group(1))
# things you can extract
network_data.keys()

# example of extracting column metadata
pd.DataFrame(network_data['col_nodes'])
```

e.g.
```
              cat-0           cat-1  cat_0_index  cat_1_index  ...  ini                 name  rank rankvar
0     Category: two    Gender: Male           24           10  ...   29     Cell Line: H1650    12       6
1     Category: two    Gender: Male           25           11  ...   28       Cell Line: H23    18      13
2     Category: two    Gender: Male           26           12  ...   27   Cell Line: CAL-12T     3       2
```

Notably the cluster for the given column is there in the `clust` column.

Hopefully this helps.
