### ISSUE TITLE
Example medium file no longer works

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/clustergrammer-web#19]
The "medium" clustergrammer web file no longer works because of `.` in the column names. The example should be updated and/or this should be fixed.

**Comment by mjnagiec** [comment]
I could not run any files on 3/9, tired "small" and my own file. Worked only after removing all "." from the txt file.

**Comment by u8sand** [comment]
Thank you for reporting this, it seems my other fix introduced a new reversion, can you please try it now

**Comment by mjnagiec** [comment]
The small-matrix works now. My file returns "502 Bad Gateway", is there a limit to the number of data points on Clustergrammer-Web? My file contains 50687

**Comment by u8sand** [comment]
Hi @mjnagiec thank you for confirming the small matrix is working for you as well.

In terms of limit on the number of data points -- we limit by RAM but the service does not seem to get killed from using too much ram but rather due to apache's queue filling up.

Your best bet might be to attempt to run this offline with the clustergrammer python package but I will see what I can do about making it work for larger files (it should at least be running out of ram, rather than crashing due to some soft limit..)

**Comment by u8sand** [comment]
I've tweaked it a bit, can you give it one more try @mjnagiec ?

**Comment by u8sand** [comment]
After doubling the memory I haven't noticed any restarts so maybe that was it.. I think what we have now is the maximum we can allocate for this. Hopefully it helps otherwise you can surely get it done with clustergrammer-js -- potentially on colab which can get you up to 12GB (vs our 8GB)
